### ISSUE TITLE
Fix : Upload Image

### ISSUE THREAD

**Issue by Zainal21** [agungprayogi291/PengaduanMasyarakat#1]
hi @agungprayogi291.. input file iso di tambahi  atribute accept supaya user gak sembarangan input file, mau tak cobo upload video bahkan script js iso ke upload walau error

 misal e ngo strict image iso  ngo ``` <input type="file" id="img" name="img" accept="image/*">```

**Comment by agungprayogi291** [comment]
terimakasih ilmunya
